### ISSUE TITLE
Increase capacity of Extra Garages

### ISSUE THREAD

**Issue by Mimonsi** [Wayzware/DepotCapacityChanger#1]
Could you update the mod to include Extra Garage of Bus Terminals also having increased capacity? 
I would also love if the sliders accepted smaller steps, e.g. 25% or 10%.

**Comment by Wayzware** [comment]
Hey, thanks for the feedback! I will look into having the changes apply to the building upgrades. 

For increasing the granularity of the sliders, can you give me an example of the value you would set with this? I was thinking the current slider settings were sufficient, but maybe I overlooked something. 😃

**Comment by Mimonsi** [comment]
Sounds great! I was thinking of this code block. In this snippet I changed the step to 25. The min and max values remain unchanged, but it is possible to more precisely adjust in steps of 25% instead of 100%. In my Gameplay I want to have 150% depot capacity most of the time, so I don't "cheat", but still increase the very low base capacity of the game.


```
        [SettingsUISlider(min = 100, max = 1000, step = 25, scalarMultiplier = 1, unit = Unit.kPercentage)]
        [SettingsUISection(CapacitySection, CapacityGroup)]
        public int BusSlider { get; set; }

        [SettingsUISlider(min = 100, max = 1000, step = 25, scalarMultiplier = 1, unit = Unit.kPercentage)]
        [SettingsUISection(CapacitySection, CapacityGroup)]
        public int TaxiSlider { get; set; }

        [SettingsUISlider(min = 100, max = 1000, step = 25, scalarMultiplier = 1, unit = Unit.kPercentage)]
        [SettingsUISection(CapacitySection, CapacityGroup)]
        public int TramSlider { get; set; }

        [SettingsUISlider(min = 100, max = 1000, step = 25, scalarMultiplier = 1, unit = Unit.kPercentage)]
        [SettingsUISection(CapacitySection, CapacityGroup)]
        public int TrainSlider { get; set; }

        [SettingsUISlider(min = 100, max = 1000, step = 25, scalarMultiplier = 1, unit = Unit.kPercentage)]
        [SettingsUISection(CapacitySection, CapacityGroup)]
        public int SubwaySlider { get; set; }
```

**Comment by Wayzware** [comment]
I've made this change in PR #2 and updated the mod on Paradox mods with these changes (mod version 1.1.0)
